### ISSUE TITLE
Pruebas de issues y Mark Down

### ISSUE THREAD

**Issue by estebanHub** [estebanHub/probandoGit#1]
**escribir con negrita**

_escribo con cursiva_

* una lista
* otra lista mas

**Comment by changomalabar** [comment]
**yo pruebo negrita también**

**Comment by changomalabar** [comment]
_yo pruebo cursiva_

**Comment by changomalabar** [comment]
- [x] cambiar un archivo de arduino

- [x] referenciar en un commit
